[package]
name = "rust_system"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu_rt_lidar = "0.1.0"
glam = { version = "0.29.2", features = ["bytemuck"] }
futures="0.3.31"
ndarray= "*"

[lib]
crate-type=["staticlib"]
